export const ListCitizensTitles = [
    "ID",
    "Họ và tên",
    "Ngày sinh",
    "Ngày mất",
    "Giới tính",
    "Dân tộc",
    " Tôn giáo",
    "Trình độ học vấn",
    "Tình trạng hôn nhân",
    "Địa chỉ",
];

export const LearningLevels = [
    "Tiểu học",
    "Trung học cơ sở",
    "Trung học phổ thông",
    "Trung cấp",
    "Cao đẳng",
    "Đại học",
    "Cao học",
];

export const Ethnics = [
    "Ba-na",
    "Bố Y",
    "Brâu",
    "Bru-Vân Kiều",
    "Chăm (Chàm)",
    "Chơ-ro",
    "Chu-ru",
    "Chứt",
    "Co",
    "Cống",
    "Cơ-ho",
    "Cơ Lao",
    "Cơ-tu",
    "Dao",
    "Ê-đê",
    "Giáy",
    "Gia-rai",
    "Gié-Triêng",
    "Hà nhì",
    "Hoa (Hán)",
    "Hrê",
    "Hmông (Mèo)",
    "Kinh (Việt)",
    "Kháng",
    "Khơ-me",
    "Khơ-mú",
    "La Chí",
    "La Ha",
    "La Hủ",
    "Lào",
    "Lô lô",
    "Lự",
    "Mạ",
    "Mảng",
    "Mường",
    "Mnông",
    "Ngái",
    "Nùng",
    "Ơ Đu",
    "Pà Thẻn",
    "Phù Lá",
    "Pu Péo",
    "Ra-glai",
    "Rơ-măm",
    "Sán Chay (Cao lan-Sán chỉ)",
    "Sán Dìu",
    "Si La",
    "Tày",
    "Tà-ôi",
    "Thái",
    "Thổ",
    "Xinh-mun",
    "Xơ-đăng",
    "Xtiêng"
];

export const Religions = [
    "Bà-la-môn giáo", 
    "Baha’I", 
    "Bửu Sơn Kỳ Hương",
    "Cao đài", 
    "Công giáo", 
    "Cơ đốc Phục lâm", 
    "Hồi giáo", 
    "Không",
    "Mặc môn", 
    "Minh lý đạo - Tam Tông Miếu", 
    "Minh Sư đạo", 
    "Phật giáo", 
    "Phật giáo Hiếu Nghĩa Tà Lơn", 
    "Phật giáo Hòa Hảo", 
    "Phật giáo Tứ Ân Hiếu nghĩa", 
    "Tịnh độ Cư sỹ Phật hội", 
    "Tin lành", 
];